config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  root 'sessions#new'

  # Sessions routes for login and logout
  get '/login', to: 'sessions#new', as: 'sign_in'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # Users routes for signup, user details, and gameplay
  resources :users, only: [:new, :create, :show]
  get '/play_game', to: 'users#play_game', as: 'play_game'
  get '/game_history', to: 'users#game_history', as: 'game_history'
  get '/exit_game', to: 'users#exit_game', as: 'exit_game'

  # Additional Sessions routes
  resources :sessions, only: [:new, :create]

  get '/display_game', to: 'users#display_game', as: 'display_game'

  # Uncomment the line below if you wish to view 'Hello, World!'
  # root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
# app/models/game.rb

class Game < ApplicationRecord
    # Define your associations, validations, and any other necessary logic here
end
  

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
    attr_accessor :quarters
  
    has_secure_password
  
    validates :username, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true, length: { minimum: 6 }
  
    # Make the presence validation conditional
    validates :quarters, presence: true, unless: -> { skip_quarters_validation }
    validates :white_dice, presence: true, unless: -> { skip_white_dice_validation }
    validates :points, presence: true, unless: -> { skip_points_validation }
  
    attr_accessor :skip_quarters_validation, :skip_white_dice_validation, :skip_points_validation
  end
  

app/controllers/application_controller.rb
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_login, except: [:new, :create, :home]
  
    private
  
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end
    helper_method :current_user
  
    def require_login
      redirect_to root_path unless current_user
    end
end
  

app/controllers/pages_controller.rb
# app/controllers/pages_controller.rb

class PagesController < ApplicationController
  def index
    @message = "Hello, World!"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user), notice: 'Login successful.'
    else
      flash.now[:alert] = 'Invalid email or password.'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# app/controllers/users_controller.rb

class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    # Set up initial conditions after signing up
    @user.quarters = 3
    @user.white_dice = 3
    @user.points = 0

    if @user.save
      # Your successful signup logic here
      redirect_to root_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    # You can add logic here if needed

    # Render the "User" page
  end

  def play_game
    # Load game settings from the form or initialize with defaults
    @num_players = params[:num_players].to_i
    @num_die_sides = params[:num_die_sides].to_i
    @num_dice = params[:num_dice].to_i

    # Validate that the required parameters are present
    if @num_players <= 0 || @num_die_sides <= 0 || @num_dice <= 0
      flash.now[:alert] = 'Please provide valid game settings.'
      render :new
      return
    end

    # Run the AutoDropDead game with the provided settings
    auto_drop_dead = AutoDropDead::AutoDropDead.new(@num_players)
    auto_drop_dead.play_game(@num_die_sides, @num_dice, @num_players)

    # [Optional] Store the game alongside the date and time the game was run
    Game.create(transcript: auto_drop_dead.transcript.join("\n"))

    # Display the game to the user
    render :play_game, locals: { transcript: auto_drop_dead.transcript }
  end

  def display_game
    # This action will render the game display page
    # You can retrieve the game data and display it here
    # Consider storing game data in an instance variable like @game_data
    :display_game
  end

  def game_history
    # Add any logic needed for displaying game history
    # Render the "Game History" page
    render :game_history
  end

  def exit_game
    # Add any cleanup or logout logic if needed
    # Redirect to the "Sign-In" page
    redirect_to sign_in_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dropdead</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<!-- app/views/pages/index.html.erb -->

<!DOCTYPE html>
<html>
<head>
  <title>Hello, World!</title>
</head>
<body>
  <h1><%= @message %></h1>
</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/display_game.html.erb
<!-- app/views/users/display_game.html.erb -->

<h2>Game Display</h2>

<!-- Display the game transcript -->
<pre><%= @transcript.join("\n") %></pre>

<%= link_to 'Play Again', play_game_path %>
<!-- <%= link_to 'Change Settings', play_game_path %> -->
<%= link_to 'Go Back', user_path(current_user) %>

app/views/users/game_history.html.erb
<!-- app/views/users/game_history.html.erb -->
<h2>Game History</h2>
<!-- Add content for displaying game history -->

app/views/users/new.html.erb
<!-- Sign-Up Page -->
<h2>Sign-Up</h2>

<%= form_with(model: @user, url: users_path) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br>

  <%= f.label :email %>
  <%= f.text_field :email %><br>

  <%= f.label :password %>
  <%= f.password_field :password %><br>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br>

  <%= f.submit "Sign-Up" %>
<% end %>

app/views/users/play_game.html.erb
<!-- app/views/users/play_game.html.erb -->

<h2>Play Game</h2>

<%= form_tag play_game_path, method: :post do %>
  <!-- your form fields for num_players, num_die_sides, num_dice -->
  <%= label_tag :num_players, 'Number of Players' %>
  <%= number_field_tag :num_players %>

  <%= label_tag :num_die_sides, 'Number of Die Sides' %>
  <%= number_field_tag :num_die_sides %>

  <%= label_tag :num_dice, 'Number of Dice' %>
  <%= number_field_tag :num_dice %>

  <%= submit_tag 'Play New Game' %>
<% end %>


<%= link_to 'Go Back', user_path(current_user) %>

app/views/users/show.html.erb
<!-- User Page -->
<h1>Welcome, <%= @user.username %></h1>

<h2>User Details</h2>
<!-- Add any user details you want to display -->

<!-- Buttons for Play New Game, View Game History, and Exit -->
<%= link_to 'Play New Game', play_game_path %><br>
<%= link_to 'View Game History', game_history_path %><br>
<%= link_to 'Exit', exit_game_path %>

<!-- <%= link_to "Sign-Out", logout_path, method: :delete %> -->